[input]

prepend_keymap = [
  { on = "<ESC>",  run = "close", desc = "Cancel input"}
]

[mgr]

prepend_keymap = [
  { on = [ "g", "w" ], run = "cd ~/Code/workspace", desc = "Go to ~/Code/workspace" },
  { on = [ "g", "r" ], run = "cd ~/Code",           desc = "Go to ~/Code" },
  { on = [ "g", "f" ], run = "cd ~/Code/dot-file",           desc = "Go to ~/Code/dot-file" },
]
