[mgr]
show_hidden = true

[opener]
edit = [
  { run = "nvim %s",  desc = "Neovim",   for = "unix", block = true},
  { run = "nvim %s",  desc = "Neovim",   for = "windows", block = true}
]

[open]
prepend_rules = [
  { url = "*.{toml, cpp, h}", use = "edit"},
]
append_rules = [
  { url = "*.md", use = "edit"},
]
