[mgr]
show_hidden = true

[opener]
edit = [
  { run = "nvim %s",  desc = "Neovim",   for = "unix", block = true},
  { run = "nvim %s",  desc = "Neovim",   for = "windows", block = true}
]

[open]
append_rule = [
  { url = "*.md", use = "edit"}
]
